// FBV FleetOS — / Live Operations Dashboard (design/dashboard.md).
// Map-first: full-bleed Leaflet map, floating fleet rail, KPI strip,
// alert ticker, translucent navy topbar (Layout handles the topbar overlay).

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import {
  Activity, AlertTriangle, ChevronLeft, KeyRound, MessageSquare,
  PanelLeft, Route, Search, ShieldCheck, Wrench,
} from 'lucide-react';
import { FleetMap } from '@/components/FleetMap';
import type { FleetMapHandle } from '@/components/FleetMap';
import { Drawer, KPIStatCard, PlateTag, StatusPill, toast } from '@/components/shared';
import { useCollection, useLiveStore } from '@/lib/store';
import { sim } from '@/lib/sim';
import { corridorById } from '@/lib/telematics';
import { cn } from '@/lib/utils';
import {
  VEHICLE_STATUS_TO_KEY, fmtDateTimeEAT, fmtNum, fmtTimeEAT,
} from '@/lib/format';
import type { LivePosition, Vehicle, VehicleStatus } from '@/lib/types';

const EASE: [number, number, number, number] = [0.22, 1, 0.36, 1];

type Filter = 'all' | VehicleStatus;

/* ---------------- live status helpers ---------------- */

function useLiveByVehicle(): Map<string, LivePosition> {
  return useLiveStore((s) => s.positions);
}

function statusOf(v: Vehicle, live?: LivePosition): VehicleStatus {
  return live?.status ?? v.status;
}

function locationSnippet(v: Vehicle, geofences: { name: string; center?: { lat: number; lng: number } }[], live?: LivePosition): string {
  if (live) {
    let best: string | null = null;
    let bestD = Infinity;
    for (const g of geofences) {
      if (!g.center) continue;
      const d = Math.hypot(g.center.lat - live.lat, g.center.lng - live.lng);
      if (d < bestD) { bestD = d; best = g.name; }
    }
    if (best && bestD < 0.02) return `at ${best}`;
    if (best) return `near ${best}`;
    return corridorById(v.simRoute).name;
  }
  return corridorById(v.simRoute).name;
}

/* ---------------- SIM chip (top-center of map) ---------------- */

function SimChipOverlay() {
  const running = useLiveStore((s) => s.running);
  return (
    <div className="pointer-events-auto absolute left-1/2 top-4 z-[650] -translate-x-1/2"
      title="Positions are generated by the built-in telematics simulator — no real devices connected.">
      <div className="glass-navy flex items-center gap-2 rounded-full border border-navy-700/60 px-3 py-1.5">
        <span className="relative flex h-1.5 w-1.5">
          {running && <span className="absolute h-full w-full rounded-full bg-accent-on-navy animate-pulse-live-ring" />}
          <span className={cn('relative h-1.5 w-1.5 rounded-full', running ? 'bg-accent-on-navy' : 'bg-inactive')} />
        </span>
        <span className="font-mono text-[11px] font-semibold tracking-[0.04em] text-white">
          TELEMATICS SIM · 2s tick
        </span>
      </div>
    </div>
  );
}

/* ---------------- fleet rail ---------------- */

function FleetRail({ vehicles, drivers, geofences, live, selectedId, onSelect, className }: {
  vehicles: Vehicle[];
  drivers: { id: string; name: string }[];
  geofences: { name: string; center?: { lat: number; lng: number } }[];
  live: Map<string, LivePosition>;
  selectedId: string | null;
  onSelect: (id: string) => void;
  className?: string;
}) {
  const [filter, setFilter] = useState<Filter>('all');
  const [q, setQ] = useState('');
  const [collapsed, setCollapsed] = useState(false);

  const counts = useMemo(() => {
    const c: Record<VehicleStatus, number> = { moving: 0, idling: 0, stopped: 0, offline: 0 };
    vehicles.forEach((v) => { c[statusOf(v, live.get(v.id))]++; });
    return c;
  }, [vehicles, live]);

  const rows = useMemo(() => {
    const needle = q.toLowerCase().trim();
    return vehicles.filter((v) => {
      if (filter !== 'all' && statusOf(v, live.get(v.id)) !== filter) return false;
      if (!needle) return true;
      const drv = drivers.find((d) => d.id === v.assignedDriverId)?.name ?? '';
      return v.plate.toLowerCase().includes(needle) || drv.toLowerCase().includes(needle);
    });
  }, [vehicles, live, filter, q, drivers]);

  const chips: { key: Filter; label: string; count: number; status?: 'ok' | 'warn' | 'inactive' | 'alert' }[] = [
    { key: 'all', label: 'All', count: vehicles.length },
    { key: 'moving', label: 'Moving', count: counts.moving, status: 'ok' },
    { key: 'idling', label: 'Idling', count: counts.idling, status: 'warn' },
    { key: 'stopped', label: 'Stopped', count: counts.stopped, status: 'inactive' },
    { key: 'offline', label: 'Offline', count: counts.offline, status: 'alert' },
  ];

  if (collapsed) {
    return (
      <div className={cn('flex w-12 flex-col items-center gap-2 rounded-drawer bg-white py-3 shadow-pop', className)}>
        <button type="button" onClick={() => setCollapsed(false)} title="Expand fleet rail"
          className="flex h-8 w-8 items-center justify-center rounded-lg text-ink-600 hover:bg-surface-muted">
          <PanelLeft size={16} />
        </button>
        <span className="font-mono text-[11px] font-bold text-ink-900 [writing-mode:vertical-rl]">FLEET · {vehicles.length}</span>
      </div>
    );
  }

  return (
    <div className={cn('flex w-[340px] max-w-[calc(100vw-32px)] flex-col rounded-drawer bg-white shadow-pop', className)}>
      <div className="flex items-center gap-2 px-4 pb-1 pt-4">
        <h2 className="text-[18px] font-bold leading-[26px] tracking-[-0.01em] text-ink-900">Fleet</h2>
        <span className="rounded-full bg-inactive-soft px-2 py-0.5 text-micro font-semibold text-inactive-on-soft">{vehicles.length}</span>
        <button type="button" onClick={() => setCollapsed(true)} title="Collapse"
          className="ml-auto flex h-7 w-7 items-center justify-center rounded-lg text-ink-400 hover:bg-surface-muted">
          <ChevronLeft size={15} />
        </button>
      </div>
      <div className="flex gap-1 overflow-x-auto px-4 py-2">
        {chips.map((c) => (
          <button key={c.key} type="button" onClick={() => setFilter(c.key)}
            className={cn('flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1 text-micro font-semibold transition-colors',
              filter === c.key
                ? c.status ? STATUS_CHIP_SOLID[c.status] : 'bg-navy-900 text-white'
                : 'bg-surface-muted text-ink-600 hover:bg-border')}>
            {c.status && filter !== c.key && <span className={cn('h-1.5 w-1.5 rounded-full', STATUS_DOT[c.status])} />}
            {c.label} <span className="font-mono">{c.count}</span>
          </button>
        ))}
      </div>
      <div className="px-4 pb-2">
        <div className="flex h-9 items-center gap-2 rounded-lg border border-border bg-surface-muted px-3">
          <Search size={14} className="shrink-0 text-ink-400" />
          <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search plate, driver…"
            className="w-full bg-transparent text-[13px] text-ink-900 outline-none placeholder:text-ink-400" />
        </div>
      </div>
      <div className="min-h-0 flex-1 overflow-y-auto px-2 pb-2">
        {rows.map((v) => {
          const p = live.get(v.id);
          const st = statusOf(v, p);
          const drv = drivers.find((d) => d.id === v.assignedDriverId)?.name ?? 'Unassigned';
          const selected = selectedId === v.id;
          return (
            <button key={v.id} type="button" onClick={() => onSelect(v.id)}
              className={cn('flex w-full items-center gap-2.5 rounded-xl px-2 text-left transition-colors duration-100',
                'h-16', selected ? 'bg-accent-soft' : 'hover:bg-surface-muted')}>
              <span className="relative flex h-2 w-2 shrink-0">
                {st === 'moving' && <span className={cn('absolute h-full w-full rounded-full animate-pulse-live-ring', STATUS_DOT[VEHICLE_STATUS_TO_KEY[st]])} />}
                <span className={cn('relative h-2 w-2 rounded-full', STATUS_DOT[VEHICLE_STATUS_TO_KEY[st]])} />
              </span>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <PlateTag plate={v.plate} />
                  <span className="truncate text-[13px] text-ink-600">{drv}</span>
                </div>
                <div className="mt-1 truncate text-[11px] leading-4 text-ink-400">
                  {locationSnippet(v, geofences, p)}
                </div>
              </div>
              <div className="shrink-0 text-right">
                {st === 'moving' ? (
                  <div className="font-mono text-[13px] font-semibold text-ink-900">{p?.speedKmh ?? 0} <span className="text-[10px] font-medium text-ink-400">km/h</span></div>
                ) : (
                  <StatusPill status={VEHICLE_STATUS_TO_KEY[st]} label={st} />
                )}
              </div>
            </button>
          );
        })}
        {rows.length === 0 && (
          <div className="px-4 py-8 text-center text-[13px] text-ink-400">No vehicles match this filter.</div>
        )}
      </div>
    </div>
  );
}

const STATUS_DOT: Record<string, string> = {
  ok: 'bg-ok', warn: 'bg-warn', alert: 'bg-alert', inactive: 'bg-inactive', info: 'bg-info',
};
const STATUS_CHIP_SOLID: Record<string, string> = {
  ok: 'bg-ok text-white', warn: 'bg-warn text-white', alert: 'bg-alert text-white', inactive: 'bg-inactive text-white', info: 'bg-info text-white',
};

/* ---------------- KPI strip ---------------- */

const SPARK_ACTIVE = [78, 80, 82, 79, 83, 85, 84, 86, 82, 85, 87, 86, 85, 86];
const SPARK_KM = [1980, 2120, 1890, 2340, 2210, 2080, 2410, 2190, 2260, 2110, 2380, 2290, 2080, 2318];
const SPARK_ALERTS = [6, 5, 8, 7, 9, 6, 10, 8, 7, 9, 11, 8, 9, 9];
const SPARK_SCORE = [89.8, 90.1, 90.4, 89.9, 90.6, 91.0, 90.8, 91.2, 91.5, 91.1, 91.3, 91.6, 91.2, 91.4];

function KpiStrip({ activePct, kmToday, openAlerts, critical, avgScore, className }: {
  activePct: number; kmToday: number; openAlerts: number; critical: number; avgScore: number; className?: string;
}) {
  const navigate = useNavigate();
  return (
    <div className={cn('flex gap-2.5', className)}>
      <KPIStatCard label="Fleet active" value={activePct} format={(v) => `${Math.round(v)}%`}
        delta="+4% vs yesterday" deltaGood spark={SPARK_ACTIVE} sparkColor="#16A34A" icon={Activity}
        onClick={() => navigate('/analytics')} className="glass-white w-40 border-white/60 p-3" />
      <KPIStatCard label="Fleet km today" value={kmToday} format={(v) => `${fmtNum(Math.round(v))} km`}
        delta="+12%" deltaGood spark={SPARK_KM} icon={Route}
        onClick={() => navigate('/trips')} className="glass-white w-40 border-white/60 p-3" />
      <KPIStatCard label="Open alerts" value={openAlerts}
        delta={critical > 0 ? `${critical} critical` : 'all minor'} deltaGood={critical === 0}
        spark={SPARK_ALERTS} sparkColor={critical > 0 ? '#DC2626' : '#F59E0B'} icon={AlertTriangle}
        onClick={() => navigate('/alerts')} className="glass-white w-40 border-white/60 p-3" />
      <KPIStatCard label="Avg safety score" value={avgScore} format={(v) => v.toFixed(1)}
        delta="+1.2 this week" deltaGood spark={SPARK_SCORE} icon={ShieldCheck}
        onClick={() => navigate('/safety')} className="glass-white w-40 border-white/60 p-3" />
    </div>
  );
}

/* ---------------- alert ticker ---------------- */

function AlertTicker({ className }: { className?: string }) {
  const alerts = useCollection('alerts');
  const navigate = useNavigate();
  const latest = useMemo(
    () => alerts.filter((a) => !a.acknowledged)
      .sort((a, b) => b.at.localeCompare(a.at)).slice(0, 3),
    [alerts],
  );
  const openCount = alerts.filter((a) => !a.acknowledged).length;
  const sevDot: Record<string, string> = { critical: 'bg-alert', major: 'bg-warn', minor: 'bg-info', info: 'bg-inactive' };

  return (
    <div className={cn('glass-navy w-[380px] max-w-[calc(100vw-32px)] overflow-hidden rounded-xl border border-navy-700/60 shadow-pop', className)}>
      <div className="flex items-center gap-2 px-3.5 py-2.5">
        <span className="text-[13px] font-semibold text-white">Live alerts</span>
        <span className="rounded-full bg-alert px-1.5 py-0.5 text-[10px] font-bold text-white">{openCount}</span>
        <button type="button" onClick={() => navigate('/alerts')}
          className="ml-auto text-[12px] font-medium text-accent-on-navy hover:underline">All alerts →</button>
      </div>
      <AnimatePresence initial={false}>
        {latest.map((a) => (
          <motion.button key={a.id} type="button"
            initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0 }}
            transition={{ duration: 0.25, ease: EASE }}
            onClick={() => navigate('/alerts')}
            className="flex h-14 w-full items-center gap-2.5 border-t border-navy-700/50 px-3.5 text-left animate-alert-flash hover:bg-navy-800/40">
            <span className={cn('h-2 w-2 shrink-0 rounded-full', sevDot[a.severity])} />
            <span className="flex-1 truncate text-[12px] leading-4 text-navy-50">{a.message}</span>
            <span className="shrink-0 font-mono text-[11px] text-navy-100/60">{fmtTimeEAT(a.at)}</span>
            <span className="shrink-0 text-[11px] font-semibold text-accent-on-navy">View</span>
          </motion.button>
        ))}
      </AnimatePresence>
      {latest.length === 0 && (
        <div className="border-t border-navy-700/50 px-3.5 py-3 text-[12px] text-navy-100/60">All clear — no unacknowledged alerts.</div>
      )}
    </div>
  );
}

/* ---------------- vehicle quick-view drawer ---------------- */

function MiniRouteStrip({ vehicleId }: { vehicleId: string }) {
  useLiveStore((s) => s.trailsVersion); // re-render on tick
  const trail = sim.trail(vehicleId);
  const W = 420, H = 160;
  let path = '';
  if (trail.length > 1) {
    const lats = trail.map((p) => p[0]);
    const lngs = trail.map((p) => p[1]);
    const [minLat, maxLat] = [Math.min(...lats), Math.max(...lats)];
    const [minLng, maxLng] = [Math.min(...lngs), Math.max(...lngs)];
    const pad = 14;
    const sx = (W - pad * 2) / Math.max(1e-9, maxLng - minLng);
    const sy = (H - pad * 2) / Math.max(1e-9, maxLat - minLat);
    const s = Math.min(sx, sy);
    path = trail.map(([lat, lng], i) => {
      const x = pad + (lng - minLng) * s;
      const y = H - pad - (lat - minLat) * s;
      return `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
    }).join(' ');
  }
  return (
    <div className="relative h-40 overflow-hidden rounded-xl bg-navy-900">
      <img src="/login-texture.svg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-60" />
      {path ? (
        <svg viewBox={`0 0 ${W} ${H}`} className="absolute inset-0 h-full w-full" preserveAspectRatio="none">
          <path d={path} fill="none" stroke="#06B6D4" strokeWidth="3" strokeLinecap="round" />
        </svg>
      ) : (
        <div className="absolute inset-0 flex items-center justify-center font-mono text-[11px] text-navy-100/60">NO TRAIL YET TODAY</div>
      )}
      <span className="absolute left-3 top-2 font-mono text-[10px] uppercase tracking-[0.08em] text-navy-100/60">Today's path</span>
    </div>
  );
}

function VehicleDrawer({ vehicle, live, onClose }: {
  vehicle: Vehicle | null;
  live: Map<string, LivePosition>;
  onClose: () => void;
}) {
  const navigate = useNavigate();
  const drivers = useCollection('drivers');
  const geofenceEvents = useCollection('geofenceEvents');
  const safetyEvents = useCollection('safetyEvents');
  const trips = useCollection('trips');

  const p = vehicle ? live.get(vehicle.id) : undefined;
  const st = vehicle ? statusOf(vehicle, p) : 'offline';
  const driver = vehicle ? drivers.find((d) => d.id === vehicle.assignedDriverId) : undefined;

  const todayKm = useMemo(() => {
    if (!vehicle) return 0;
    return trips.filter((t) => t.vehicleId === vehicle.id && t.startAt.slice(0, 10) === '2026-07-28')
      .reduce((s, t) => s + t.distanceKm, 0);
  }, [trips, vehicle]);

  const events = useMemo(() => {
    if (!vehicle) return [];
    const rows: { at: string; text: string; sev?: string }[] = [];
    geofenceEvents.filter((e) => e.vehicleId === vehicle.id).slice(0, 2).forEach((e) => {
      rows.push({ at: e.at, text: `Geofence ${e.type} — ${e.geofenceId.replace('gf-0', '#')}` });
    });
    safetyEvents.filter((e) => e.vehicleId === vehicle.id).slice(0, 2).forEach((e) => {
      rows.push({ at: e.at, text: `${e.type.replace(/_/g, ' ')} — ${e.location}`, sev: e.severity });
    });
    return rows.sort((a, b) => b.at.localeCompare(a.at)).slice(0, 3);
  }, [vehicle, geofenceEvents, safetyEvents]);

  return (
    <Drawer open={!!vehicle} onClose={onClose}
      title={vehicle && (
        <div className="flex flex-wrap items-center gap-2">
          <PlateTag plate={vehicle.plate} />
          <span className="text-[13px] font-normal text-ink-600">{vehicle.model}, {vehicle.year}</span>
          <StatusPill status={VEHICLE_STATUS_TO_KEY[st]} label={st} pulse={st === 'moving'} />
          <KeyRound size={15} className={p?.ignition ? 'text-ok' : 'text-alert'} />
        </div>
      )}>
      {vehicle && (
        <motion.div initial="hidden" animate="show"
          variants={{ show: { transition: { staggerChildren: 0.04 } } }}
          className="flex flex-col gap-4">
          {/* live stat grid */}
          <motion.div variants={{ hidden: { opacity: 0, y: 6 }, show: { opacity: 1, y: 0 } }}
            className="grid grid-cols-2 gap-2">
            {[
              { label: 'Speed', value: `${p?.speedKmh ?? 0} km/h` },
              { label: 'Odometer', value: `${fmtNum(vehicle.odometerKm)} km` },
              { label: 'Engine hours', value: `${fmtNum(vehicle.engineHours)} h` },
              { label: 'Fuel', value: `${vehicle.fuelLevelPct}%` },
            ].map((s) => (
              <div key={s.label} className="rounded-lg border border-border bg-surface-muted/50 px-3 py-2.5">
                <div className="text-[11px] font-medium uppercase tracking-[0.06em] text-ink-400">{s.label}</div>
                <div className="font-mono text-[15px] font-semibold text-ink-900">{s.value}</div>
                {s.label === 'Fuel' && (
                  <div className="mt-1 h-1.5 overflow-hidden rounded-full bg-border">
                    <div className={cn('h-full rounded-full', vehicle.fuelLevelPct < 25 ? 'bg-alert' : 'bg-accent')}
                      style={{ width: `${vehicle.fuelLevelPct}%` }} />
                  </div>
                )}
              </div>
            ))}
          </motion.div>

          <motion.div variants={{ hidden: { opacity: 0, y: 6 }, show: { opacity: 1, y: 0 } }}>
            <MiniRouteStrip vehicleId={vehicle.id} />
          </motion.div>

          <motion.div variants={{ hidden: { opacity: 0, y: 6 }, show: { opacity: 1, y: 0 } }}
            className="flex items-center justify-between rounded-lg bg-navy-50 px-3 py-2 font-mono text-[12px] font-medium text-navy-800">
            <span>Today</span>
            <span>{trips.filter((t) => t.vehicleId === vehicle.id && t.startAt.slice(0, 10) === '2026-07-28').length || 6} trips · {fmtNum(Math.round(todayKm || 412))} km · 38 min idle</span>
          </motion.div>

          <motion.div variants={{ hidden: { opacity: 0, y: 6 }, show: { opacity: 1, y: 0 } }}
            className="grid grid-cols-2 gap-2">
            <button type="button" onClick={() => navigate(`/tracking?replay=${vehicle.plate.replace(/\s/g, '')}`)}
              className="flex h-10 items-center justify-center gap-2 rounded-lg bg-navy-900 text-[13px] font-semibold text-white transition-all hover:bg-navy-800 active:scale-[0.97]">
              <Route size={15} /> Replay today's route
            </button>
            <button type="button" onClick={() => navigate('/maintenance')}
              className="flex h-10 items-center justify-center gap-2 rounded-lg border border-border text-[13px] font-semibold text-ink-900 transition-all hover:bg-surface-muted active:scale-[0.97]">
              <Wrench size={15} /> Create work order
            </button>
            <button type="button"
              onClick={() => toast({ title: 'Message queued', body: `Message to ${driver?.name ?? 'driver'} will send when device reconnects.`, status: 'info' })}
              className="flex h-10 items-center justify-center gap-2 rounded-lg border border-border text-[13px] font-semibold text-ink-900 transition-all hover:bg-surface-muted active:scale-[0.97]">
              <MessageSquare size={15} /> Message driver
            </button>
            <button type="button" onClick={() => navigate(`/vehicles/${vehicle.id}`)}
              className="flex h-10 items-center justify-center gap-2 rounded-lg text-[13px] font-semibold text-accent-strong hover:underline">
              Open vehicle 360° →
            </button>
          </motion.div>

          <motion.div variants={{ hidden: { opacity: 0, y: 6 }, show: { opacity: 1, y: 0 } }}>
            <div className="pb-1 text-[12px] font-medium uppercase tracking-[0.06em] text-ink-400">Last events</div>
            <div className="flex flex-col divide-y divide-border/70 rounded-lg border border-border">
              {events.length === 0 && <div className="px-3 py-3 text-[12px] text-ink-400">No recent events.</div>}
              {events.map((e, i) => (
                <div key={i} className="flex items-center gap-2 px-3 py-2.5">
                  <span className={cn('h-1.5 w-1.5 shrink-0 rounded-full',
                    e.sev === 'critical' ? 'bg-alert' : e.sev === 'major' ? 'bg-warn' : 'bg-inactive')} />
                  <span className="flex-1 truncate text-[12px] capitalize text-ink-900">{e.text}</span>
                  <span className="shrink-0 font-mono text-[11px] text-ink-400">{fmtDateTimeEAT(e.at).split(', ')[1] ?? fmtTimeEAT(e.at)}</span>
                </div>
              ))}
            </div>
          </motion.div>
        </motion.div>
      )}
    </Drawer>
  );
}

/* ---------------- main dashboard ---------------- */

export default function Dashboard() {
  const vehicles = useCollection('vehicles');
  const drivers = useCollection('drivers');
  const geofences = useCollection('geofences');
  const alerts = useCollection('alerts');
  const live = useLiveByVehicle();
  useLiveStore((s) => s.trailsVersion);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const mapRef = useRef<FleetMapHandle>(null);

  const plates = useMemo(() => new Map(vehicles.map((v) => [v.id, v.plate])), [vehicles]);
  const trails = useMemo(() => sim.trails(), [live]);

  const onSelect = useCallback((id: string) => {
    setSelectedId(id);
    const p = useLiveStore.getState().positions.get(id);
    if (p) mapRef.current?.flyTo(p.lat, p.lng, 15);
  }, []);

  // "Resuming live feed…" when tab was hidden > 60s
  useEffect(() => {
    let hiddenAt = 0;
    const h = () => {
      if (document.hidden) hiddenAt = Date.now();
      else if (hiddenAt && Date.now() - hiddenAt > 60_000) {
        toast({ title: 'Resuming live feed…', body: 'Catching up on telematics positions.', status: 'info' });
        hiddenAt = 0;
      }
    };
    document.addEventListener('visibilitychange', h);
    return () => document.removeEventListener('visibilitychange', h);
  }, []);

  // red edge glow once for new critical alerts
  const [glowKey, setGlowKey] = useState(0);
  const lastAlertAt = useRef<string>('');
  useEffect(() => {
    const newest = alerts.filter((a) => !a.acknowledged && a.severity === 'critical')
      .sort((a, b) => b.at.localeCompare(a.at))[0];
    if (newest && newest.at > lastAlertAt.current) {
      if (lastAlertAt.current) setGlowKey((k) => k + 1);
      lastAlertAt.current = newest.at;
    }
  }, [alerts]);

  const stats = useMemo(() => {
    const nonOffline = vehicles.filter((v) => statusOf(v, live.get(v.id)) !== 'offline').length;
    const activePct = vehicles.length ? (nonOffline / vehicles.length) * 100 : 0;
    const open = alerts.filter((a) => !a.acknowledged).length;
    const critical = alerts.filter((a) => !a.acknowledged && a.severity === 'critical').length;
    const avgScore = drivers.length ? drivers.reduce((s, d) => s + d.safetyScore, 0) / drivers.length : 0;
    return { activePct, open, critical, avgScore };
  }, [vehicles, live, alerts, drivers]);

  // fleet km today: base + live accrual from moving vehicles
  const [kmAccrued, setKmAccrued] = useState(0);
  const prevPos = useRef<Map<string, LivePosition>>(new Map());
  useEffect(() => {
    let addKm = 0;
    live.forEach((p, id) => {
      const prev = prevPos.current.get(id);
      if (prev && p.status === 'moving') {
        addKm += Math.hypot(p.lat - prev.lat, p.lng - prev.lng) * 111;
      }
      prevPos.current.set(id, p);
    });
    if (addKm > 0 && addKm < 5) setKmAccrued((k) => k + addKm);
  }, [live]);

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3, ease: EASE }}
      className="relative h-full w-full overflow-hidden">
      {/* map canvas */}
      <div key={glowKey} className={cn('absolute inset-0', glowKey > 0 && 'animate-edge-glow')}>
        <FleetMap
          ref={mapRef}
          className="absolute inset-0"
          positions={live}
          plates={plates}
          selectedId={selectedId}
          onVehicleClick={onSelect}
          geofences={geofences}
          trails={trails}
        />
      </div>

      <SimChipOverlay />

      {/* KPI strip — top-right (scrollable row on small screens) */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.12, ease: EASE }}
        className="absolute right-4 top-4 z-[640] hidden xl:block">
        <KpiStrip activePct={stats.activePct} kmToday={2318 + kmAccrued} openAlerts={stats.open}
          critical={stats.critical} avgScore={stats.avgScore} />
      </motion.div>

      {/* fleet rail — floating left panel (desktop) */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.06, ease: EASE }}
        className="absolute bottom-4 left-4 top-4 z-[640] hidden lg:flex">
        <FleetRail vehicles={vehicles} drivers={drivers} geofences={geofences}
          live={live} selectedId={selectedId} onSelect={onSelect} className="h-full" />
      </motion.div>

      {/* alert ticker — bottom-left of map (desktop) */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.18, ease: EASE }}
        className="absolute bottom-4 left-[388px] z-[640] hidden lg:block">
        <AlertTicker />
      </motion.div>

      {/* mobile: KPI row + bottom sheet */}
      <div className="absolute inset-x-2 top-2 z-[640] lg:hidden">
        <div className="overflow-x-auto pb-1">
          <KpiStrip activePct={stats.activePct} kmToday={2318 + kmAccrued} openAlerts={stats.open}
            critical={stats.critical} avgScore={stats.avgScore} className="w-max" />
        </div>
      </div>
      <MobileSheet
        vehicles={vehicles} drivers={drivers} geofences={geofences}
        live={live} selectedId={selectedId} onSelect={onSelect}
      />
      <div className="absolute inset-x-2 bottom-[84px] z-[630] lg:hidden">
        <AlertTicker className="w-full max-w-none" />
      </div>

      {/* vehicle quick-view drawer */}
      <VehicleDrawer
        vehicle={vehicles.find((v) => v.id === selectedId) ?? null}
        live={live}
        onClose={() => setSelectedId(null)}
      />
    </motion.div>
  );
}

/* mobile bottom sheet with snap points (peek 72 / half / full) */
function MobileSheet(props: React.ComponentProps<typeof FleetRail>) {
  const [snap, setSnap] = useState<'peek' | 'half' | 'full'>('peek');
  const heights = { peek: 72, half: Math.round(window.innerHeight * 0.5), full: Math.round(window.innerHeight * 0.86) };
  return (
    <motion.div
      drag="y"
      dragConstraints={{ top: 0, bottom: 0 }}
      dragElastic={0.12}
      onDragEnd={(_, info) => {
        if (info.offset.y < -60) setSnap(snap === 'peek' ? 'half' : 'full');
        else if (info.offset.y > 60) setSnap(snap === 'full' ? 'half' : 'peek');
      }}
      animate={{ height: heights[snap] }}
      transition={{ duration: 0.25, ease: EASE }}
      className="absolute inset-x-0 bottom-0 z-[645] flex flex-col overflow-hidden rounded-t-2xl bg-white shadow-pop lg:hidden"
    >
      <button type="button" onClick={() => setSnap(snap === 'peek' ? 'half' : snap === 'half' ? 'full' : 'peek')}
        className="flex h-6 shrink-0 items-center justify-center">
        <span className="h-1 w-10 rounded-full bg-border" />
      </button>
      <div className="min-h-0 flex-1">
        <FleetRail {...props} className="h-full w-full max-w-none rounded-none shadow-none" />
      </div>
    </motion.div>
  );
}
